### ISSUE TITLE
json parsing error

### ISSUE THREAD

**Issue by tatramaco** [GoFetchAD/GoFetch#4]
Despite using the specified version of the Bloodhound client I am still getting the following error when running Invoke-GoFetch

An error occurred while enumerating through a collection: Object reference not set to an instance of an object

Can I get a steer on how to fix this ?

**Comment by talmaor** [comment]
1. Did you find any messages in the log file that could help?
2. Is the input json file includes an attack path?
3. Can you share the command you are running and the input file?

**Comment by tatramaco** [comment]
1. Couldn't create GoFetch path - An error occurred while enumerating through a collection: Object reference not set to an instance of an object..
2. I tried 2 attack paths, 1 from user to user and 1 from machine to DC. It's in my bullshit lab so jason files attached.
[BloodHoundExport.txt](https://github.com/GoFetchAD/GoFetch/files/1229485/BloodHoundExport.txt)
[graph.txt](https://github.com/GoFetchAD/GoFetch/files/1229487/graph.txt)

3. PS> .\Invoke-GoFetch.ps1 -PathToBloodHoundGraph .\graph.json

**Comment by talmaor** [comment]
I couldn't reproduce this here and I do get GoFetch paths from both of files (Attached the path from graph.txt).
Are you running PowerShell 3 or at least .Net 3.5?
Can you check what line the exception happens...?

> {"final":[],"path":[{"label":"HasSession","targetName":"tom@fox1.net","sourceName":"Client1.domain1.test.local"},{"label":"AdminTo","sourceName":"TOM@FOX1.NET","targetName":"INTER-1.FOX1.NET","id":49254},{"label":"HasSession","sourceName":"INTER-1.FOX1.NET","targetName":"DICK@FOX1.NET","id":49261},{"label":"AdminTo","sourceName":"DICK@FOX1.NET","targetName":"INTER-2.FOX1.NET","id":49257},{"label":"HasSession","sourceName":"INTER-2.FOX1.NET","targetName":"ADM_BOB@FOX1.NET","id":49262},{"label":"MemberOf","sourceName":"ADM_BOB@FOX1.NET","targetName":"DOMAIN ADMINS@FOX1.NET","id":49246}],"exceptions":[],"startNode":{"name":"Client1"},"status":{}}

**Comment by tatramaco** [comment]
I am running PS2 and .Net 4.5.2.

Let me rebuild a new VM and see....
